#!/bin/sh

# @kludge: make it possible to restart awesome without running this script twice
if [ -f '/tmp/.awesomestart' ]; then
  echo "Awesome has already been started. Aborting."
  exit 1
fi

touch '/tmp/.awesomestart'

## Quad monitors
# @todo: only run this on fourside
xrandr --output DP-1    --mode 1920x1080 --pos 1080x0    --rotate inverted \
       --output DVI-I-1 --mode 1920x1080 --pos 0x1080    --rotate left \
       --output DVI-D-1 --mode 1920x1080 --pos 3000x1080 --rotate right \
       --output HDMI-1  --mode 1920x1080 --pos 1080x1080 --rotate normal


## GNOME PolicyKit and Keyring
eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &

## Set root window colour
hsetroot -solid "#2E3436" &

## Wallpaper and compositor
(\
nitrogen --restore && \
cb-compositor --start && \
sleep 5s
) &

## Volume keys daemon
xfce4-volumed &

## Enable power management
xfce4-power-manager &

## Mixer
pavucontrol &

## Detect and configure touchpad. See 'man synclient' for more info.
#if egrep -iq 'touchpad' /proc/bus/input/devices; then
    #synclient VertEdgeScroll=1 &
    #synclient TapButton1=1 &
#fi

## Start xscreensaver
xscreensaver -no-splash &

## Start Clipboard manager
#(sleep 3s && clipit) &

## Adjust the values according to your preferences.
xset r rate 250 30 &

## Turn on/off system beep
xset b off &

## Run the conky
#conky -q &

## Synapse
synapse --startup
