#!/bin/sh

##
# This script remasters my CrunchBang system.
##

# require root to run this script
if [[ $EUID -ne 0 ]]; then
echo "This script must be run as root" 1>&2
  exit 1
fi

echo 'Removing unwanted packages...'
apt-get --assume-yes remove clipit
apt-get --assume-yes remove fortune-mod
apt-get --assume-yes remove geany
apt-get --assume-yes remove gftp
apt-get --assume-yes remove gmrun
apt-get --assume-yes remove pycrust
apt-get --assume-yes remove thunar
apt-get --assume-yes remove xedit
apt-get --assume-yes remove xmag

# install system packages
echo 'Installing system packages...'
# apt-get --assume-yes install thunderbird
# apt-get --assume-yes install xul-ext-lightning
# apt-get --assume-yes install arandr
apt-get --assume-yes install ack-grep
apt-get --assume-yes install build-essential
apt-get --assume-yes install chromium-browser
apt-get --assume-yes install curl
apt-get --assume-yes install fontforge
apt-get --assume-yes install imagemagick
apt-get --assume-yes install irrsi
apt-get --assume-yes install libnss3-tools
apt-get --assume-yes install nmap
apt-get --assume-yes install openvpn
apt-get --assume-yes install pinta
apt-get --assume-yes install pcmanfm
apt-get --assume-yes install python-fontforge
apt-get --assume-yes install rake
apt-get --assume-yes install ruby
apt-get --assume-yes install terminator
apt-get --assume-yes install tidy
apt-get --assume-yes install tmux
apt-get --assume-yes install tree
apt-get --assume-yes install unp
apt-get --assume-yes install vim-nox
apt-get --assume-yes install vlc vlc-plugin-pulse
apt-get --assume-yes install xclip

# cleann up
apt-get autoclean
apt-get autoremove

echo 'Creating directories...'
cd ~; mkdir desktop src; cd src; mkdir bin conf www

echo 'Removing default directories...'
rm -rf ~/backup ~/templates

# install vim
echo 'Installing vim...'
mkdir -p ~/.vim/bundle/
cd ~/.vim/bundle/
git clone https://github.com/gmarik/vundle
chown -R $USER:$USER ~/.vim

# generate SSH keys
echo 'Generating SSH keys...'
ssh-keygen -t rsa -C "chris@chris-allen-lane.com"

# notify
echo 'Packages installed.  Remember to install the following as well:'
echo ''
echo ' * Google Chrome'
echo ' * LastPass'
echo ' * TrueCrypt'
echo ' * Vagrant'
echo ' * VirtualBox'
echo ''
echo 'Remember to sync your browser plugins as well.'

# Browser sync
chromium-browser https://lastpass.com
chromium-browser https://www.google.com
