execute pathogen#infect()

" stuff to improve
" - powerline 
" - autocomplete
" - backspace (Ctrl+w)
" - vimrc formatting
" - skybison?
" - command-t
" - changing tabs
" - pasting from the system clipboard

" ----- Color Scheme -----
set guifont=inconsolata
:colorscheme molokai
let g:molokai_original = 1

filetype plugin indent on
highlight ColorColumn ctermbg=4 " change the highlight to darkblue
highlight CursorLine ctermbg=0  " change the highlight to darkblue
scriptencoding utf-8
syntax on

" ----- Command Line -----
if has('cmdline_info')
	set ruler                   " show the ruler
	set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%) " a ruler on steroids
	set showcmd                 " show partial commands in status line and selected characters/lines in visual mode  
endif

" ----- Status Line -----
if has('statusline')
	set laststatus=2
	set statusline=%<%f\
	set statusline+=%w%h%m%r
	set statusline+=%{fugitive#statusline()}
	set statusline+=\ [%{&ff}/%Y]
	set statusline+=\ [%{getcwd()}]
	set statusline+=%=%-14.(%l,%c%V%)\ %p%%
endif

" ----- General -----
"set pastetoggle=<F12>           " pastetoggle (sane indentation on pastes)
"set scrolljump=5                " lines to scroll when cursor leaves screen
"set scrolloff=3                 " minimum lines to keep above and below cursor
"set showmatch                   " show matching brackets/parenthesis
"set spell                       " spell checking on
set autochdir
set autoindent                  " indent at the same level of the previous line
set backspace=indent,eol,start  " backspace for dummies
set colorcolumn=80,120          " highlight the 80th column
set cursorline                  " highlight current line
set expandtab                   " tabs are spaces, not tabs
set foldenable                  " auto fold code
set foldmethod=indent
set foldnestmax=3
set hidden
set hlsearch                    " highlight search terms
set ignorecase                  " case insensitive search
set incsearch                   " find as you type search
set linespace=0                 " No extra spaces between rows
set matchpairs+=<:>             " match, to be used with %
set mouse=a                     " automatically enable mouse usage
set nobackup
set noswapfile
set nowb
set nowrap                      " wrap long lines
set nu                          " Line numbers on
set shiftwidth=4                " an indentation every four columns
set si
set smartcase                   " case sensitive when uc present
set smarttab
set softtabstop=4               " let backspace delete indent
set t_Co=256
set tabstop=4                   " an indentation every four columns
set virtualedit=onemore         " allow for cursor beyond last character
set whichwrap=b,s,h,l,<,>,[,]   " backspace and cursor keys wrap to
set wildmenu                    " show list instead of just completing
set wildmode=list:longest,full  " command <Tab> completion, list matches, then longest common part, then all.
set winminheight=0              " windows can be 0 line high

let mapleader = ","

cmap Tabe tabe

:imap jk <Esc>
:imap JK <Esc>
:imap kj <Esc>
:imap KJ <Esc>
:imap <C-BS> <C-W>

nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k
nmap <C-L> <C-W>l
nmap <C-j> }
nmap <C-k> {
nmap <silent> <leader>f :NERDTreeToggle<CR> 
nmap <silent> <leader>t :TlistToggle<CR> 

"nnoremap tm  :tabm<Space>
nnoremap <silent> <leader>d :bd<CR> 
nnoremap <silent> <leader>h :split<CR> 
nnoremap <silent> <leader>q :q<CR> 
nnoremap <silent> <leader>sc :e /tmp/scratch.txt<CR> 
nnoremap <silent> <leader>v :vsplit<CR> 
nnoremap <silent> <leader>w :w<CR> 
nnoremap <silent> <space> :noh<CR> 
nnoremap j gj
nnoremap k gk
nnoremap td :tabclose<CR>
nnoremap tf :tabfirst<CR>
nnoremap tj :tabnext<CR>
nnoremap tk :tabprev<CR>
nnoremap tl :tablast<CR>
nnoremap tt :tabnew<CR>
nnoremap tn :tabnext<CR>
vnoremap < <gv
vnoremap <silent> <leader>s :sort<CR> 
vnoremap <silent> <leader>te :Tab /=<CR> 
vnoremap > >gv

" specify custom file types
au BufNewFile,BufRead *.json set filetype=javascript
au BufNewFile,BufRead *.md.erb set filetype=markdown

" open the tag list browser on the right
let Tlist_Use_Right_Window = 1
