#!/bin/sh

# fire xrandr if four monitors are detected
if [ `xrandr -d :0 -q | grep "connected" | wc -l` -eq 4 ]
then
  xrandr --output DP-1 --mode 1920x1080 --pos 1080x0 --rotate inverted --output DVI-I-1 --mode 1920x1080 --pos 0x1080 --rotate left --output DVI-D-1 --mode 1920x1080 --pos 3000x1080 --rotate right --output HDMI-1 --mode 1920x1080 --pos 1080x1080 --rotate normal
fi

# set the background
/bin/sh ~/.fehbg

# start the compositor
xcompmgr -cfF -D 3 &

# audio
pavucontrol &

# synapse
synapse -s &

# screensaver
xscreensaver -no-splash &

# start awesome
exec awesome
